name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to build e.g. gpu-notebook'
        required: true
        default: 'gpu-notebook'
      tag:
        description: 'Tag to build e.g. cuda11.8.0-ubuntu22.04'
        required: true
        default: 'cuda11.8.0-ubuntu22.04'
      registry:
        description: Container registry to use
        type: choice
        required: false
        default: quay.io
        options:
         - ghcr.io
         - quay.io
      push:
        description: Push the image to the registry
        type: boolean
        required: false
        default: true
      parent_image:
        description: 'Based image to build on'
        required: false
        default: ''
      parent_image_tag:
        description: 'Based image tag to build on'
        required: false
        default: ''

jobs:
  manual_trigger:
    secrets: inherit
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: ${{ inputs.parent_image }}
      parent-variant: ${{ inputs.parent_image_tag }}
      image: ${{ inputs.image }}
      variant: ${{ inputs.tag }}
      context: ${{ inputs.image }}/${{ inputs.tag }}/
      registry: ${{ inputs.registry }}
      push: ${{ inputs.push }}
      runs-on: ubuntu-latest


